### ISSUE TITLE
search問題

### ISSUE THREAD

**Issue by geo-finds** [leedom92/hexo-theme-leedom#1]
您好: 

        套用您的模板,在搜尋時沒有辦法呈現您網頁搜尋的結果會跳出`The search.xml file was not found, please refer to:`

**Comment by leedom92** [comment]
@geo-finds 你好

请安装 [hexo-generator-search](https://github.com/wzpan/hexo-generator-search) 依赖插件
```sh
npm install hexo-generator-search -S
```

在项目根目录下的 `_config.yml` 添加或编辑以下配置即可:
```yml
search:
  path: search.xml
  field: post
  content: true
```
详情见[配置](https://github.com/leedom92/hexo-theme-leedom/blob/master/README.zh-CN.md#%E9%85%8D%E7%BD%AE)

谢谢你的反馈！
